MvcNetCorePaginacionRegistros/Controllers/PaginacionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using MvcNetCorePaginacionRegistros.Models;
using MvcNetCorePaginacionRegistros.Repositories;

namespace MvcNetCorePaginacionRegistros.Controllers
{
    public class PaginacionController : Controller
    {
        public RepositoryHospital repo;

        public PaginacionController(RepositoryHospital repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> PaginarRegistroVistaDepartamento(int? posicion)
        {
            if(posicion == null)
            {
                posicion = 1;
            }
            int numRegistros = await this.repo.GetNumeroRegistrosVistaDepartamentosAsync();

            int siguiente = posicion.Value + 1;
            if(siguiente > numRegistros)
            {
                siguiente = numRegistros;
            }

            int anterior = posicion.Value - 1;
            if(anterior < 1)
            {
                anterior = 1;
            }

            ViewData["ULTIMO"] = numRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;

            VistaDepartamento departamentos =
                await this.repo.GetVistaDepartamentoAsync(posicion.Value);

            return View(departamentos);
        }

        public async Task<IActionResult> PaginarGrupoVistaDepartamento(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            
            int numRegistros = 
                await this.repo.GetNumeroRegistrosVistaDepartamentosAsync();

            ViewData["REGISTROS"] = numRegistros;

            List<VistaDepartamento> departamentos =
                await this.repo.GetGrupoVistaDepartamentoAsync(posicion.Value);

            return View(departamentos);
        }

        public async Task<IActionResult> PaginarGrupoDepartamentos(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            int numRegistros =
                await this.repo.GetNumeroRegistrosVistaDepartamentosAsync();

            ViewData["REGISTROS"] = numRegistros;

            List<Departamento> departamentos =
                await this.repo.GetGrupoDepartamentosAsync(posicion.Value);

            return View(departamentos);
        }

        public async Task<IActionResult> PaginarGrupoEmpleados(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }

            int numRegistros =
                await this.repo.GetEmpleadosCountAsync();

            ViewData["REGISTROS"] = numRegistros;

            List<Empleado> empleados =
                await this.repo.GetGrupoEmpleadosAsync(posicion.Value);

            return View(empleados);
        }

        public async Task<IActionResult> EmpleadosOficio(int? posicion, string oficio)
        {
            if (posicion == null)
            {
                posicion = 1;
                return View();
            }
            else
            {
                List<Empleado> empleados = await this.repo.GetEmpleadosOficioAsync(posicion.Value, oficio);
                int registros = await this.repo.GetEmpleadosOficioCountAsync(oficio);

                ViewData["REGISTROS"] = registros;
                ViewData["OFICIO"] = oficio;

                return View(empleados);
            }
        }

        [HttpPost]
        public async Task<IActionResult> EmpleadosOficio(string oficio)
        {
            List<Empleado> empleados = await this.repo.GetEmpleadosOficioAsync(1, oficio);
            int registros = await this.repo.GetEmpleadosOficioCountAsync(oficio);

            ViewData["REGISTROS"] = registros;
            ViewData["OFICIO"] = oficio;

            return View(empleados);
        }

        public async Task<IActionResult> EmpleadosOficioOut(int? posicion, string oficio)
        {
            if (posicion == null)
            {
                posicion = 1;
                return View();
            }
            else
            {
                ModelEmpleadosOficio model = await this.repo.GetEmpleadosOficioOutAsync(posicion.Value, oficio);

                ViewData["REGISTROS"] = model.NumeroRegistros;
                ViewData["OFICIO"] = oficio;

                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> EmpleadosOficioOut(string oficio)
        {
            ModelEmpleadosOficio model = await this.repo.GetEmpleadosOficioOutAsync(1, oficio);

            ViewData["REGISTROS"] = model.NumeroRegistros;
            ViewData["OFICIO"] = oficio;

            return View(model);
        }

        public async Task<IActionResult> Details(int id, int posicion)
        {
            Departamento departamento = await this.repo.FindDepartamento(id);
            Empleado empleado = await this.repo.GetEmpleadoDepartamento(posicion, id);
            ModelDepartamentoEmpleado departamentoEmpleado = new ModelDepartamentoEmpleado()
            {
                Empleado = empleado,
                Departamento = departamento
            };

            int numRegistros = await this.repo.GetNumeroRegistros(id);
            ViewData["REGISTROS"] = numRegistros;            

            int siguiente = posicion + 1;
            if (siguiente > numRegistros)
            {
                siguiente = numRegistros;
            }

            int anterior = posicion - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }

            ViewData["ULTIMO"] = numRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;

            return View(departamentoEmpleado);
        }
    }
}

MvcNetCorePaginacionRegistros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCorePaginacionRegistros</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCorePaginacionRegistros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCorePaginacionRegistros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Paginación Departamentos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item"
                                       asp-controller="Paginacion"
                                       asp-action="PaginarRegistroVistaDepartamento">
                                        Paginar Individual Vista
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-controller="Paginacion"
                                       asp-action="PaginarGrupoVistaDepartamento">
                                        Paginar Grupo Vista
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-controller="Paginacion"
                                       asp-action="PaginarGrupoDepartamentos">
                                        Paginar Grupo Departamentos
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-controller="Paginacion"
                                       asp-action="EmpleadosOficio">
                                        Paginar Empleados Oficio
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-controller="Paginacion"
                                       asp-action="EmpleadosOficioOut">
                                        Paginar Empleados Oficio Out
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcNetCorePaginacionRegistros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>